# Generated by Django 5.0.7 on 2024-07-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_manager",
        ),
    ]
