# Generated by Django 5.0.7 on 2024-07-28 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                ("surname", models.CharField(max_length=50, verbose_name="Отчество")),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Комментарий")),
                ("is_blocked", models.BooleanField(default=False, verbose_name="Заблокирован")),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="Logs",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_and_time_last_send", models.DateTimeField(verbose_name="Дата и время последней отправки")),
                ("status_send", models.BooleanField(default=False, verbose_name="Статус отправки")),
                (
                    "server_message",
                    models.TextField(blank=True, max_length=200, null=True, verbose_name="Ответ почтового сервера"),
                ),
            ],
            options={
                "verbose_name": "Лог",
                "verbose_name_plural": "Логи",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=150, verbose_name="Тема письма")),
                ("body", models.TextField(verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="SendMail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_start_send", models.DateTimeField(verbose_name="Дата и время первой отправки рассылки")),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("once", "Один раз в день"),
                            ("weekly", "Один раз в неделю"),
                            ("monthly", "Один раз в месяц"),
                        ],
                        max_length=10,
                        verbose_name="Периодичность рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Создано"), ("sent", "Отправлено"), ("end", "Завершено")],
                        default="created",
                        max_length=10,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(related_name="clients", to="services.client", verbose_name="Клиенты"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="services.message", verbose_name="Сообщение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "permissions": [
                    ("disable_sendmail", "Может отключать рассылки"),
                    ("block_user", "Может блокировать пользователей"),
                ],
            },
        ),
    ]
