# Generated by Django 5.0.7 on 2024-07-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sendmail",
            options={
                "permissions": [("disable_sendmail", "Может отключать рассылки")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.RemoveField(
            model_name="client",
            name="is_blocked",
        ),
        migrations.AddField(
            model_name="sendmail",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
    ]
