# Generated by Django 5.0.7 on 2024-08-09 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_client_owner_sendmail_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendmail",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="services.message",
                verbose_name="Сообщение",
            ),
        ),
    ]
