# Generated by Django 5.0.7 on 2024-08-09 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_alter_sendmail_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sendmail",
            name="message",
        ),
        migrations.AddField(
            model_name="message",
            name="send_mail",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="services.sendmail", verbose_name="Рассылка"
            ),
            preserve_default=False,
        ),
    ]
