# Generated by Django 5.0.7 on 2024-08-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_remove_sendmail_message_message_send_mail"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendmail",
            name="date_end_send",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время завершения рассылки"),
        ),
    ]
