# Generated by Django 5.0.7 on 2024-08-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_sendmail_date_end_send"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendmail",
            name="date_end_send",
            field=models.DateTimeField(verbose_name="Дата и время завершения рассылки"),
        ),
    ]
