# Generated by Django 5.0.7 on 2024-08-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_alter_sendmail_date_end_send"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendmail",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("0 0 * * *", "Один раз в день"),
                    ("0 0 * * 0", "Один раз в неделю"),
                    ("0 0 1 * *", "Один раз в месяц"),
                ],
                max_length=10,
                verbose_name="Периодичность рассылки",
            ),
        ),
    ]
