# Generated by Django 5.0.7 on 2024-08-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_alter_sendmail_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendmail",
            name="periodicity",
            field=models.CharField(
                choices=[("* * *", "Один раз в день"), ("* * 0", "Один раз в неделю"), ("1 * *", "Один раз в месяц")],
                max_length=10,
                verbose_name="Периодичность рассылки",
            ),
        ),
    ]
