# Generated by Django 5.0.7 on 2024-08-21 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0010_alter_sendmail_periodicity"),
    ]

    operations = [
        migrations.AddField(
            model_name="logs",
            name="send_mail",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="services.sendmail", verbose_name="Рассылка"
            ),
            preserve_default=False,
        ),
    ]
